server:
  port: 7001  #该 Module 的端口号。
eureka:
  server:
    enable-self-preservation: false # false 关闭 Eureka 的自我保护机制，默认是开启,一般不建议修改
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称，单机（集群）部署需要修改 hosts 文件，路径：C:/Windows/System32/drivers/etc/hosts
  client:
    register-with-eureka: false    #false表示不向注册中心注册自己。
    fetch-registry: false          #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版服务注册中心